<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\file_replace_modal\Controller\FileReplaceModalController::getModal()
 */
function file_replace_modal_form_file_replace_form_alter(&$form, FormStateInterface $form_state) {
  $args = $form_state->getBuildInfo()['args'] ?? [];
  if ($args[0] === 'use_ajax') {
    \Drupal::service('file_replace_modal.form')
      ->ajaxifyForm($form, $form_state);
  }
}

/**
 * Implements hook_field_widget_FIELD_TYPE_form_alter().
 */
function file_replace_modal_field_widget_file_generic_form_alter(&$element, FormStateInterface $form_state, $context) {
  \Drupal::service('file_replace_modal.form')
    ->widgetAlter($element, $context);
}
